# Build and Deploy a Node.JS Express App

trigger:
- master

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Docker Image Name
  dockerImageName: 'abdulmujeeb/hellonode:latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
      displayName: 'npm install, build and test'

    - task: SonarCloudPrepare@1
      displayName: "Run SAST using SonarCloud"
      inputs:
        SonarCloud: 'node-sast-scan'
        organization: '$(organization)'
        projectKey: '$(projectKey)'
        projectName: '$(projectName)'
        projectVersion: '$(Build.BuildNumber)'

    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud code analysis'

    - task: SonarCloudPublish@1
      displayName: 'Publish SonarCloud quality gate results'

    - script: |
        npm run test --if-present --reporter mocha-junit-reporter
      displayName: 'Run Mocha Tests'

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        repository: $(dockerImageName)
        command: build
        Dockerfile: Dockerfile

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
