# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  vmImageName: 'ubuntu-latest'
  dockerImageName: 'hellonodecode'
  tag: v1
  containerRegistry: 'Azure Registry'


steps:

#  - task: Docker@2
#    displayName: Login to ACR
#    inputs:
#      command: login
#      containerRegistry: acr_connection_1

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: $(containerRegistry)

  - task: Docker@2
    displayName: Build Docker Image
    inputs:
        repository: $(dockerImageName)
        command: build
        Dockerfile: Dockerfile
        tags: |
          $(tag)

  - script: |
        curl -s https://ci-tools.anchore.io/inline_scan-v0.4.1 | bash -s -- -p -r $(dockerImageName):$(tag)
    displayName: 'Scan Docker Image for Vulnerabilities'


  - task: Docker@2
    displayName: Push Docker Image
    inputs:
        repository: $(dockerImageName)
        command: push
        Dockerfile: Dockerfile
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish the project -- Release'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      
      

