# Build and Deploy a Node.JS Express App

trigger:
- master

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Docker Image Name
  dockerImageName: 'abdulmujeeb/hellonode'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
      displayName: 'npm install, build and test'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'node-sast-scan'
        organization: 'mjborg'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'node-sast-scan'
        cliProjectName: 'node-sast-scan'
        cliSources: '.'

    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud code analysis'
    
    - task: SonarCloudPublish@1
      displayName: 'Publish SonarCloud quality gate results'

    - script: |
        npm run test --if-present --reporter mocha-junit-reporter
      displayName: 'Run Mocha Tests'

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        repository: $(dockerImageName)
        command: build
        Dockerfile: Dockerfile
        tags: latest
      
    - script: |
        curl -s https://ci-tools.anchore.io/inline_scan-v0.4.1 | bash -s -- -p -r $(dockerImageName)
      displayName: 'Scan Docker Image for Vulnerabilities'

    - task: WhiteSource Bolt@19
      displayName: "Run OSS Scan using Whitesource Bolt"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
